// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtckv4lc1KbHPRy7uZCQPyX0KU843MAPw',
    appId: '1:507273750996:web:d21bf7e4bdfe0727260e41',
    messagingSenderId: '507273750996',
    projectId: 'testing-311d5',
    authDomain: 'testing-311d5.firebaseapp.com',
    storageBucket: 'testing-311d5.firebasestorage.app',
    measurementId: 'G-LJWPVKG512',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4r-l59b9X5WyHyry45tgD-VaWm7NJ8xU',
    appId: '1:507273750996:android:1cf5f080e2a1f6ca260e41',
    messagingSenderId: '507273750996',
    projectId: 'testing-311d5',
    storageBucket: 'testing-311d5.firebasestorage.app',
  );
}
